# Default values for springline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

component: flink-autoscaler

replicaCount: 1

image:
  repository: hcr.data.here.com
  path: olp-pm/flink-autoscaler
  tag:
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: olp-pm-readonly-pull-secret

service:
  # "ClusterIP" or "LoadBalancer"
  type: LoadBalancer
  # use this if you wish to register the ELB with a friendly name - only effective when type is LoadBalancer
#  dnsName: {{ Release.Name }}{{ .Values.service.dnsTail }}
  port: 80
  targetPort: 8000
  portName: api

deployment:
#  env:
#  - name: RUST_LOG
#    value: "FOO"
#  - name: RUST_BACKTRACE
#    value: "1"
#  - name: POLAR_LOG
#    value: "info"
  aaaClientSecretsName: "pipeline-monitor-aaa-client-credentials"
  accountSecretsName: "pipeline-monitor-accounting-properties"
  enableProbes: true
  nodeGroup: "nonresilient"
  taskManagerdeployment: "statefulset"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi

#tolerations:
#  - key: workload
#    operator: Equal
#    value: ""
#    effect: NoSchedule

#affinity:
#  podAntiAffinity:
#    preferredDuringSchedulingIgnoredDuringExecution:
#      - weight: 100
#        podAffinityTerm:
#          labelSelector:
#            matchExpressions:
#              - key: app
#                operator: In
#                values:
#                  - {{ include "common.name" . }}
#          topologyKey: kubernetes.io/hostname

probes:
  enabled: true
  httpGet:
    scheme: HTTP
    port: 80
    readinessPath: /health
    livenessPath: /health
    livenessInterval: 120000

application:
  kubernetes:
    patch_settle_timeout_secs: 300

  sensor:
    flink:
      metric_orders:
        flow:
          source:
            name:

  eligibility:
    template_data:
      cooling_secs: 600
      stable_secs: 900

  decision:
    template_data:
      max_healthy_relative_lag_velocity: 3.0
      max_healthy_lag: 1000000
      min_task_utilization: 0.6
      evaluate_duration_secs: 120

  governance:
    rules:
      min_parallelism:
      max_parallelism:
      min_cluster_size:
      max_cluster_size:
      min_scaling_step:
      max_scaling_step:

  action:
    taskmanager:
      cull_ratio: 0.75
      kubernetes_api:
        api_timeout_secs: 290
    flink:
      polling_interval_secs: 10
      restart:
        operation_timeout_secs: 120

global:
  annotations: {}

  pipeline:
    id:
    versionId:
    templateId:
    jobId:
    customerBillingTag:
    billingClientAppId:

  convention:
    jobPrefix: "job-"
    jobManagerSuffix: "-jm"
    taskManagerSuffix: "-tm"
    serviceSuffix: "-svc"
