apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2022-06-01T16:45:11Z"
  generation: 1
  labels:
    app: autoscaler
  name: autoscaler-k8s-api-cidr-egress
spec:
  podSelector:
    matchLabels:
#      role: {{ include "common.fullname" . }}
#    matchLabels:
#      app.kubernetes.io/name: {{ include "common.name" . }}
      app.kubernetes.io/instance: {{ include "common.fullname" . }}
#      app.kubernetes.io/component: {{ .Chart.Name }}
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.116.0.0/16
#    - ipBlock:
#        cidr: 10.116.21.32/32
#    - ipBlock:
#        cidr: 10.116.13.208/32
#    - ipBlock:
#        cidr: 10.116.5.101/32
  policyTypes:
  - Egress
