apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-as
  labels:
{{ include "common.labels" . | indent 4 }}
    app: {{ include "common.name" . }}
    component: {{ .Values.component }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
    prometheus.io/path: "/metrics"
    prometheus.io/port: '9898'
    prometheus.io/scrapehifreq: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "common.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "common.labels" . | indent 8 }}
    spec:
#      affinity:

#        preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 100
#            podAffinityTerm:
#              labelSelector:
#                matchExpressions:
#                  - key: app
#                    operator: In
#                    values:
#                      - {{ include "common.name" . }}
#              topologyKey: kubernetes.io/hostname
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "springline.serviceAccountName" . }}
      nodeSelector:
        workload: {{ .Values.deployment.nodeGroup | quote }}
      tolerations:
      - key: workload
        operator: Equal
        value: {{ .Values.deployment.nodeGroup | quote }}
        effect: NoSchedule
      containers:
      - name: flink-autoscaler
        image: {{ .Values.image.repository }}/{{ .Values.image.path }}:{{ required ".Values.image.tag is not set" .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/app/springline", "--search-path", "/app/resources:/opt/springline/resources"]
        env:
        - name: APP_ENVIRONMENT
          value: "cluster"
        - name: RUST_LOG
          value: {{ default "info" .Values.deployment.log.level }}
        - name: RUST_BACKTRACE
          value: {{ default "1" .Values.deployment.log.backtrace | quote }}
        - name: POLAR_LOG
          value: {{ default "info" .Values.deployment.log.polar }}
        ports:
        - containerPort: 80
{{- if .Values.deployment.enableProbes }}
        readinessProbe:
          httpGet:
            path: "/health/ready"
            scheme: "HTTP"
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: "/health/live"
            scheme: "HTTP"
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 360
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
{{- end }}
        resources:
          requests:
            cpu: 5m
            memory: 50Mi
          limits:
            cpu: 20m
            memory: 50Mi
        volumeMounts:
        - name: autoscaler-config
          mountPath: "/opt/springline/resources"
        - name: {{ include "common.name" . }}-aaa-credentials
          mountPath: "/opt/springline/credentials"
        - name: {{ include "common.name" . }}-accounting
          mountPath: "/opt/springline/accounting"
      volumes:
      - name: autoscaler-config
        configMap:
          name: {{ include "common.name" . }}-config
          items:
          - key: config
            path: cluster.yaml
          - key: decision_basis
            path: chart_decision_basis.polar
      - name: {{ include "common.name" . }}-aaa-credentials
        secret:
          secretName: {{ required "Values.deployment.aaaClientSecretsName is not set" .Values.deployment.aaaClientSecretsName }}
      - name: {{ include "common.name" . }}-accounting
        secret:
          secretName: {{ .Values.deployment.accountSecretsName }}