{{- if eq .Values.service.type "LoadBalancer" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.fullname" . }}-api-nw-plcy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.name" . }}
      app.kubernetes.io/instance: {{ include "common.fullname" . }}
      app.kubernetes.io/component: {{ .Chart.Name }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
        - protocol: TCP
          port: 9898
  {{- end }}