apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.fullname" . }}
  labels:
{{ include "common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "springline.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
