apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "springline.fullname" }}
  labels:
{{ include "springline.labels" | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - statefulsets
      - deployments
    verbs:
      - get
      - list
      - watch
      - update
      - patch