{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "springline.serviceAccountName" . }}
  labels:
{{ include "common.labels" . | indent 4 }}
{{- end -}}
