[package]
name = "springline"
version = "0.1.0"
authors = ["Damon Rolfs <drolfs@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dmrolfs/springline-rs/springline"
description = """
Autoscaling driver for Flink servers.
"""
categories = [
  "hardware-support",
]
keywords = ["autoscaling", "flink", "stream", "data", "processing",]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "springline"
path = "src/main.rs"

[dependencies]
proctor = { git = "https://github.com/dmrolfs/proctor-rs", branch = "main" }
anyhow = "1.0"
approx = "0.5"
async-trait = "0.1"
axum = "0.3"
axum-debug = "0.1"
cast_trait_object = "0.1"
chrono = "0.4"
clap = { version = "3.0.0-beta.5", features = ["yaml"] }
# until ron feature and builder fns in *published* config-rs
config = { git = "https://github.com/dmrolfs/config-rs" } # until ron feature and builder fns in *published* config-rs
#config = { version = "^0.11", default_features = true, features = ["ron"] }
#config = { version = "^0.11" }
console = "0.15"
dashmap = "4.0"
dialoguer = { version = "0.9", features = ["fuzzy-select"] }
enum-display-derive = "0.1"
fuzzy-matcher = "0.3"
hyper = { version = "0.14", features = ["server", "tcp", "stream"] }
itertools = "0.10"
lazy_static = "1.4"
maplit = "1.0"
nalgebra = "0.29"
num-traits = "0.2"
num_cpus = "1.13"
once_cell = "1.8"
oso = "0.22"
polar-core = "*"
pretty-snowflake = { git = "https://github.com/dmrolfs/pretty-snowflake-rs" }
prometheus = { version = "0.13", features = ["process"] }
prometheus-static-metric = "0.5"
regex = "1.5"
reqwest = { version = "0.11", features = ["json", "multipart"] }
reqwest-middleware = "0.1"
reqwest-retry = "0.1"
ron = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
serde_with = { version = "1.11", features = ["chrono", "json", "macros"] }
serde-transcode = "1.1"
settings_loader = { git = "https://github.com/dmrolfs/settings-loader-rs", features = ["http"] }
splines = "4.0"
tailcall = "*"
thiserror = "1.0"
tokio = { version = "1.13", features = ["full", "net"] }
tower = { version = "0.4", features = ["timeout", "limit"] }
tower-http = { version = "0.1", features = ["trace"] }
tracing = "0.1"
tracing-flame = "*"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
trim-margin = "*"

[dev-dependencies]
pretty_assertions = "1.0.0"
claim = "0.5.0"
mockall = "0.10.2"
tokio-test = "0.4.2"
serde_test = "1.0.130"
fake = { version = "2.4.3", features = ["chrono"] }
