{
 "title": "Drive Filtering Autoscaling - ASCL",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "selector",
    "query": "pipelineId=\"7de2037f-4fe3-466d-b2d7-ab92954f966c\""
   },
   {
    "name": "max_healthy_relative_lag_velocity",
    "query": "${VAR_MAX_HEALTHY_RELATIVE_LAG_VELOCITY}"
   }
  ]
 },
 "panels": [
  { "title": "Flink Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task Managers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_cluster_nr_task_managers{$selector}) or on() vector(0)",
     "legendFormat": "nr-task-managers"
    }
   ]
  },
  {
   "title": "Relative Lag Velocity Stat Panel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_source_relative_lag_velocity_rolling_avg{$selector}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Source Records Consumed Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_source_records_consumed_rate{$selector}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Max Task CPU Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(springline_metric_catalog_cluster_task_cpu_load{$selector}) or on() vector(0)) * 100"
    }
   ]
  },
  {
   "title": "Max Task Heap Memory Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(springline_metric_catalog_cluster_task_heap_memory_used{$selector})/sum(springline_metric_catalog_cluster_task_heap_memory_committed{$selector})) * 100"
    }
   ]
  },
  {
   "title": "Workload (records in per sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_records_in_per_sec{$selector}) or on() vector(0)",
     "legendFormat": "records-in-per-sec"
    }
   ]
  },
  {
   "title": "Source Backpressure (millis / sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_source_back_pressure_time_rolling_avg{$selector}) by(window_secs)",
     "legendFormat": "{{window_secs}}"
    }
   ]
  },
  {
   "title": "Nonsource Task Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1000 - sum(springline_metric_catalog_flow_idle_time_millis_per_sec{$selector}) or on() vector(0)) / 1000 * 100",
     "legendFormat": "nr-task-managers"
    }
   ]
  },
  {
   "title": "Nonsource Task Idle Time (ms/s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_idle_time_millis_per_sec{$selector}) or on() vector(0)",
     "legendFormat": "nr-task-managers"
    }
   ]
  },
  {
   "title": "Total Source Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_source_total_lag_rolling_avg{$selector}) or on() vector(0)",
     "legendFormat": "total-lag"
    }
   ]
  },
  {
   "title": "Relative Lag Velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_source_relative_lag_velocity_rolling_avg{$selector}) or on() vector(0)",
     "legendFormat": "relative-lag-velocity"
    }
   ]
  },
  {
   "title": "Workload (records in per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_records_in_per_sec{$selector}) or on() vector(0)",
     "legendFormat": "records-in-per-sec"
    }
   ]
  },
  {
   "title": "Source Records Consumed Rate (records per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_source_records_consumed_rate{$selector}) or on() vector(0)",
     "legendFormat": "records-in-per-sec"
    }
   ]
  },
  { "title": "Rescale Decisions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Springline Phase Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(springline_stage_eval_time_sum{$selector}) by(stage)/sum(springline_stage_eval_time_count{$selector}) by (stage))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(springline_act_is_rescaling)",
     "legendFormat": "is_rescaling"
    }
   ]
  },
  {
   "title": "Rescale Decision Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(springline_decision_scaling_decision_count{$selector, decision=\"up\"}) by(reason)",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "(-1 * sum(springline_decision_scaling_decision_count{$selector, decision=\"down\"}) by(reason))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Last Decision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(springline_decision_rescale_decision{$selector})"
    }
   ]
  },
  {
   "title": "Springline Phase Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(springline_stage_eval_time_sum{$selector}) by(stage)/sum(springline_stage_eval_time_count{$selector}) by (stage))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Consumer Telemetry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_source_is_consumer_telemetry_populated{$selector})",
     "legendFormat": "is_empty"
    }
   ]
  },
  {
   "title": "Rescale Decision Heatmap",
   "type": "heatmap",
   "description": "Decision intensity over time.\n1: Rescale Up\n0: No Action\n-1: Rescale Down",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 34 },
   "targets": [
    {
     "expr": "sum(springline_decision_rescale_decision{$selector})"
    }
   ]
  },
  {
   "title": "Clipping Point",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(springline_planning_parallelism_clipping_point{$selector})",
     "legendFormat": "clipping_point"
    }
   ]
  },
  {
   "title": "Planning Forecasting Context",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(springline_planning_ctx_forecasting_restart_secs{$selector}) by(direction)",
     "legendFormat": "restart_{{direction}}"
    },
    {
     "expr": "sum(springline_planning_ctx_forecasting_max_catch_up_secs{$selector})",
     "legendFormat": "max_catch_up"
    },
    {
     "expr": "sum(springline_planning_ctx_forecasting_recovery_valid_secs{$selector})",
     "legendFormat": "recovery_valid"
    }
   ]
  },
  {
   "title": "Springline Eligibility - Rescale Ineligible Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(springline_eligibility_policy_ineligible_decisions_count{$selector}[1m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Clipping Handler State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(springline_planning_parallelism_clipping_state{$selector})",
     "legendFormat": "state"
    }
   ]
  },
  {
   "title": "Springline Rescale Action Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(springline_act_rescale_action_time_seconds_sum{$selector}) by (action) / sum(springline_act_rescale_action_time_seconds_count{$selector}) by (action))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Rescale Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(springline_phase_act_errors{$selector, disposition=\"Failed\"}) by(action)",
     "legendFormat": "{{action}}::failed"
    },
    {
     "expr": "sum(springline_phase_act_errors{$selector, disposition=\"Ignored\"}) by(action)",
     "legendFormat": "{{action}}::ignored"
    },
    {
     "expr": "sum(springline_phase_act_errors{$selector, disposition=\"Recovered\"}) by(action)",
     "legendFormat": "{{action}}::recovered"
    }
   ]
  },
  { "title": "Springline Operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Springline Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(springline_engine_process_memory{$selector}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(springline_engine_system_total_memory{$selector})",
     "legendFormat": "total_memory"
    },
    {
     "expr": "sum(springline_engine_system_used_memory{$selector})",
     "legendFormat": "used_memory"
    },
    {
     "expr": "sum(springline_engine_system_available_memory{$selector})",
     "legendFormat": "available_memory"
    },
    {
     "expr": "sum(springline_engine_system_free_memory{$selector  })",
     "legendFormat": "free_memory"
    },
    {
     "expr": "sum(springline_engine_system_free_swap{$selector})",
     "legendFormat": "free_swap"
    },
    {
     "expr": "sum(springline_engine_system_total_swap{$selector})",
     "legendFormat": "total_swap"
    },
    {
     "expr": "sum(springline_engine_system_used_swap)",
     "legendFormat": "used_swap"
    }
   ]
  },
  {
   "title": "Performance History Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(springline_planning_performance_history_entry_count{$selector})",
     "legendFormat": "entries"
    }
   ]
  },
  {
   "title": "Consumer Telemetry Populated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(springline_metric_catalog_flow_source_is_consumer_telemetry_populated{$selector})",
     "legendFormat": "consumer_telemetry"
    }
   ]
  },
  {
   "title": "Clipping Point",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum(springline_planning_parallelism_clipping_point{$selector})",
     "legendFormat": "clipping_point"
    }
   ]
  },
  {
   "title": "Sense Phase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flink query active jobs duration, event rate [1/s]",
     "type": "heatmap",
     "description": "Heat map representing the distribution of Flink active jobs query duration. \n\nAt each point in time, each cell was hit with an average rate of times, averaged across observation periods of 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (le) (rate(springline_flink_active_jobs_time_bucket{$selector}[30s])) \n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flink Job sensor duration, event rate [1/s]",
     "type": "heatmap",
     "description": "Heat map representing the distribution of Flink Job sensor duration. \n\nAt each point in time, each cell was hit with an average rate of times, averaged across observation periods of 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum by (le) (rate(springline_flink_sensor_time_bucket{$selector, flink_scope=\"Job\"}[30s]))\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flink query Task Manager admin duration, event rate [1/s]",
     "type": "heatmap",
     "description": "Heat map representing the distribution of Flink active jobs query duration. \n\nAt each point in time, each cell was hit with an average rate of times, averaged across observation periods of 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (le) (rate(springline_flink_query_taskmanager_admin_time_bucket{$selector}[30s])) \n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flink TaskManager sensor duration, event rate [1/s]",
     "type": "heatmap",
     "description": "Heat map representing the distribution of Flink TaskManager sensor duration. \n\nAt each point in time, each cell was hit with an average rate of times, averaged across observation periods of 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by (le) (rate(springline_flink_sensor_time_bucket{$selector, flink_scope=\"TaskManager\"}[30s]))\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flink Tasks Vertex sensor duration, event rate [1/s]",
     "type": "heatmap",
     "description": "Heat map representing the distribution of Flink Tasks Vertex sensor duration. \n\nAt each point in time, each cell was hit with an average rate of times, averaged across observation periods of 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by (le) (rate(springline_flink_vertex_sensor_time_bucket{$selector, flink_scope=\"Tasks\"}[30s])) \n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flink Jobs Vertex sensor available metrics duration, event rate [1/s]",
     "type": "heatmap",
     "description": "Heat map representing the distribution of Flink Jobs Vertex available metrics duration. \n\nAt each point in time, each cell was hit with an average rate of times, averaged across observation periods of 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum by (le) (rate(springline_flink_vertex_sensor_avail_telemetry_time_bucket{$selector, flink_scope=\"Jobs\"}[30s])) \n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flink query job detail duration, event rate [1/s]",
     "type": "heatmap",
     "description": "Heat map representing the distribution of Flink job detail query duration. \n\nAt each point in time, each cell was hit with an average rate of times, averaged across observation periods of 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum by (le) (rate(springline_flink_query_job_detail_time_bucket{$selector}[30s])) \n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flink Tasks Vertex sensor metrics picklist duration, event rate [1/s]",
     "type": "heatmap",
     "description": "Heat map representing the distribution of Flink Jobs Vertex metrics picklist duration. \n\nAt each point in time, each cell was hit with an average rate of times, averaged across observation periods of 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum by (le) (rate(springline_flink_vertex_sensor_metric_picklist_time_bucket{$selector, flink_scope=\"Tasks\"}[30s])) \n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flink query Uploaded Jars duration, event rate [1/s]",
     "type": "heatmap",
     "description": "Heat map representing the distribution of Flink uploaded jars query duration. \n\nAt each point in time, each cell was hit with an average rate of times, averaged across observation periods of 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum by (le) (rate(springline_flink_uploaded_jars_time_bucket{$selector}[30s])) \n",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}