---
engine:
  machine_id: 1
  node_id: 1

http:
  host: localhost

flink:
  label: local_flink
#  job_manager_host: localhost
  max_retries: 0
  pool_idle_timeout_secs: 60
  pool_max_idle_per_host: 5

kubernetes:
  client: infer

sensor:
  flink:
    metrics_initial_delay_secs: 10

eligibility:
  template_data:
    cooling_secs: 60

decision:
  template_data:
    max_healthy_cpu_load: 0.0006
    min_healthy_cpu_load: 0.0003

plan:
  performance_repository:
    storage: file
    storage_path: "./tmp"

action:
  action_timeout_secs: 60
  taskmanager:
    kubernetes_api:
      polling_interval_secs: 5
  flink:
    polling_interval_secs: 3
    savepoint:
      directory: "s3a://my/flink/savepoints"