---
engine:
  machine_id: 7
  node_id: 3

flink:
  label: dr-springline-demo
#  job_manager_host: host.lima.internal

kubernetes:
#  client: cluser_env
  client: infer
  patch_settle_timeout_secs: 10

http:
  host: localhost

eligibility:
  template_data:
    cooling_secs: 60

decision:
  template_data:
    max_healthy_cpu_load: 0.0006
    min_healthy_cpu_load: 0.0003
