---
engine:
  machine_id: 7
  node_id: 3

flink:
  job_manager_host: dr-springline-jm-0

kubernetes:
#  client: cluser_env
  client: infer
  patch_settle_timeout_secs: 60

http:
  host: 0.0.0.0

#eligibility:
#  template_data:
#    cooling_secs: 60

decision:
  template_data:
    max_healthy_cpu_load: 0.016
    min_healthy_cpu_load: 0.012

plan:
  performance_repository:
    storage: file
    storage_path: "/var/tmp"
