---
engine:
  machine_id: 7
  node_id: 3

flink:
  job_manager_host: dr-springline-jm-0

kubernetes:
#  client: cluser_env
  client: infer
  patch_settle_timeout_secs: 60

http:
  host: 0.0.0.0

#eligibility:
#  template_data:
#    cooling_secs: 60

#decision:
# template_data:
#   max_healthy_relative_lag_velocity: 3.0
#   min_task_utilization: 0.6
#   evaluate_duration_secs: 60

plan:
  performance_repository:
    storage: file
    storage_path: "/var/tmp"
