[package]
name = "springline-transcode"
version = "0.1.0"
authors = ["Damon Rolfs <drolfs@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dmrolfs/springline-rs/springline"
description = """
Transcode configuration files between supported formats.
"""
categories = [
  "hardware-support",
]
keywords = ["autoscaling", "flink", "stream", "data", "processing",]
edition = "2021"

[[bin]]
name = "transcode"
path = "src/main.rs"

[dependencies]
springline = { path = "../springline", version = "*" }
# proctor = { git = "https://github.com/dmrolfs/proctor-rs", branch = "main" }
 anyhow = "1.0"
# approx = "0.5.0"
# async-trait = "0.1.51"
# axum = "0.3.1"
# axum-debug = "0.1.0"
# cast_trait_object = "0.1.3"
# chrono = "0.4.19"
# clap = { version = "3.0.0-beta.5", features = ["yaml"] }
# until ron feature and builder fns in *published* config-rs
# config = { git = "https://github.com/dmrolfs/config-rs" } # until ron feature and builder fns in *published* config-rs
#config = { version = "^0.11", default_features = true, features = ["ron"] }
#config = { version = "^0.11" }
# console = "0.15.0"
# dashmap = "4.0.2"
# dialoguer = { version = "0.9.0", features = ["fuzzy-select"] }
# enum-display-derive = "0.1.1"
# fuzzy-matcher = "0.3.7"
# hyper = { version = "0.14.14", features = ["server", "tcp", "stream"] }
# itertools = "0.10.1"
# lazy_static = "1.4.0"
# maplit = "1.0.2"
# nalgebra = "0.29.0"
# num-traits = "0.2.14"
# num_cpus = "1.13.0"
# once_cell = "1.8.0"
# oso = "0.22.1"
# polar-core = "0.22.1"
# pretty-snowflake = { git = "https://github.com/dmrolfs/pretty-snowflake-rs" }
# prometheus = { version = "0.13.0", features = ["process"] }
# prometheus-static-metric = "0.5.1"
# regex = "1.5.4"
# reqwest = { version = "0.11.6", features = ["json", "multipart"] }
# reqwest-middleware = "0.1.2"
# reqwest-retry = "0.1.3"
 ron = "0.7"
# serde = "1.0.130"
 serde_json = "1.0"
# serde_repr = "0.1.7"
# serde_with = { version = "1.11.0", features = ["chrono", "json", "macros"] }
 serde-transcode = "1.1"
# settings_loader = { git = "https://github.com/dmrolfs/settings-loader-rs", features = ["http"] }
# splines = "4.0.3"
# tailcall = "0.1"
# thiserror = "1.0.30"
# tokio = { version = "1.13.0", features = ["full", "net"] }
# tower = { version = "0.4.10", features = ["timeout", "limit"] }
# tower-http = { version = "0.1.1", features = ["trace"] }
# tracing = "0.1.29"
# tracing-flame = "0.1.0"
# tracing-futures = "0.2.5"
# tracing-subscriber = { version = "0.3.1", features = ["env-filter", "json"] }
# trim-margin = "0.1.0"

# [dev-dependencies]
# pretty_assertions = "1.0.0"
# claim = "0.5.0"
# mockall = "0.10.2"
# tokio-test = "0.4.2"
# serde_test = "1.0.130"
# fake = { version = "2.4.3", features = ["chrono"] }
