---
imagePullSecrets:
  - name: "olp-pm-readonly-pull-secret"
#service:
#  dnsTail: -api-dev.plm.platform.in.here.com
deployment:
  log:
    level: "info,springline::flink=debug,springline::kubernetes=trace,springline::phases::act=trace,kube=trace,kube_client=trace"
    polar: "info"
    backtrace: "1"

application:
  action:
    taskmanager:
      kubernetes_api:
        api_timeout_secs: 450
    flink:
      polling_interval_secs: 15

global:
  realm: "olp-here"
  pipeline:
    id: "7de2037f-4fe3-466d-b2d7-ab92954f966c"
    versionId: "b7c5d122-77b6-4bd7-98cc-8316aa77a826"
    templateId: "3ec2f478-9488-4390-86eb-d746c6551e0c"
    jobId: "58e48f1a-8d0a-478d-89a4-950bec9e4cb9"
    customerBillingTag: "2460zDz92553"
    billingClientAppId: "patappid"
