service:
  type: "CLusterIP"

deployment:
  accountingSecretsName: "${FLINK_AUTOSCALER_ACCOUNTING_SECRET:-flink-autoscaler-accounting-properties}"
  imagePullSecretsName: "olp-pm-olp-pm-bot-pull-secret"
  monitorNodeGroup: "${FLINK_AUTOSCALER_NODE_GROUP:-default}"
  livenessProbeMaxTimeSinceLastCheck: "${LP_MAX_LAST_CHECK:-2147483647}"

config:
  # increase frequency compared to default so tests can run within reasonable time
#  refreshIntervalMillis: 3000
#  heartbeatIntervalMillis: 30000
#  timeoutClusterReadyMillis: 30000
#  timeoutJobReadyMillis: 15000
#  timeoutJobStoppingMillis: 30000
#  timeoutJobFailingMillis: 30000
#  timeoutMasterMissingMillis: 30000
#  aaa:
#    timeout:
#      connect: 15000
#      read: 30000
#  flink1XJobManager:
#    timeout:
#      connect: 15000
#      read: 30000
#  pipelineService:
#    timeout:
#      connect: 15000
#      read: 30000
    # assume mocking
    url: "${PSV2_MOCK_URL:-http://mockserver-pipeline-monitor-pat.plm.platform.in.here.com:80/mockPipelineService}"
    # fr the time being disable authentication
    dummyAuthentication: false
    tokenCacheMinutes: 60
    accountUrl: "${AAA_MOCK_URL:-http://mockserver-pipeline-monitor-pat.plm.platform.in.here.com:80/mockAaa}"
    realm: "${HERE_AUTH_REALM:-}"

global:
  docker:
    host: "hcr.data.here.com"
  pipeline:
    # Override in pipeline template chart
    id: "00000000-0000-0000-0000-100801000020"
    projectHrn: "hrn:here-dev:authorization::olp-here:project/narya-test-0000"
    versionId: "00000000-0000-0000-2000-000801000020"
    templateId: "00000000-0000-0000-3000-000801000020"
    jobId: "00000000-0000-0000-0000-400801000020"
    realm: "plmpatrealm"
    customerBillingTag: "patbilling"
    billingClientAppId: "patappid"
  cluster:
    # override the cluster master endpoint generated by helm, and use mock
    url: "${MASTER_MOCK_URL:-http://mockserver-pipeline-monitor-pat.plm.platform.in.here.com:80/mockFlinkJobManager}"
    port:
    # PAT build will override the below for testing each cluster type
    type: "${PIPELINE_TEST_TYPE:-FLINK_1_X}"
    cpuOverheadCores: 0.5
    memoryOverheadMi: 64
    config:
      supervisor:
        memoryMi: 1024
        cpu: 1
        diskGi: 10
      worker:
        memoryMi: 2048
        cpu: 2
        diskGi: 20
      numberOfWorkers: 4
  dpClusterId: "int-1-aws-eu-west-1"
  pipelineTerminationGracePeriodSeconds: 10
